services:
  db:
    image: mysql:8.0
    container_name: burger_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_restaurant
      MYSQL_USER: user_app
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    container_name: burger_pma
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data:
